### ISSUE TITLE
error running run.sh

### ISSUE THREAD

**Issue by hargan123** [Hamahmi/kaldi-tut#1]
Hi Hamahmi. Thanks for the tutorial! I am a newbie to git and kaldi, pardon the naive questions.
I could get till step5  following the readme.md; but not quite beyond.

Specifically the following:

step 6: This seems to be already done in path.sh; nothing to add
step 7: which files to change the path. Nowhere */hamahmi/* could be found

When running run.sh I get the following error:
![Capture](https://user-images.githubusercontent.com/48414775/54088926-20b7ae80-4389-11e9-940f-740109ee229f.PNG)

**Comment by hargan123** [comment]
Proceeding with kaldi-for-dummies as instructed, did Acoustic Data and Language data Preparation tasks within /egs/kaldi-tut instead of  /egs/digits. Used utt2spk, text and wav.scp files from ~/egs/kaldi-tut/digits-audio/test and train folders in data preparation.

Tools attachmnt not done as it seems to be alrady present after cloning kaldi-tut.

Now when ./run.sh is given, error comes as follows:
Kindly help.
![Capture2](https://user-images.githubusercontent.com/48414775/54089354-16e47a00-438e-11e9-9b0d-5749f14df758.PNG)

**Comment by Hamahmi** [comment]
it seems that parse_options.sh is not there
